"""Lightweight perception components that do not require a trained model."""

from bot.perception.turn_owner import (
    DEFAULT_AVATAR_LAYOUT,
    AvatarRoiLayout,
    CardCountDelta,
    HighlightDetection,
    HybridTurnOwnerDetector,
    HybridTurnOwnerConsensus,
    NormalizedRect,
    TurnOwnerDetection,
    TurnOwnerConsensusResult,
    YellowHighlightDetector,
)
from bot.perception.table_state import (
    StateAcceptancePolicy,
    TableStateAssembler,
    TableStateConsensus,
    TableStateConsensusResult,
)
from bot.perception.buttons import (
    ButtonTemplate,
    TemplateButtonDetector,
    load_gameplay_button_detector,
)
from bot.perception.yolo_cards import YoloCardConfigurationError, YoloCardDetector
from bot.perception.ocr import OcrConfigurationError, OcrText, TesseractOcr
from bot.perception.fan_cards import FanCardTemplateRecognizer, FanGeometry
from bot.perception.ui_evaluation import (
    UiEvaluationStatus,
    UiButtonState,
    UiPredictedButtonState,
    UiOcrField,
    UiPredictedOcrField,
    UiGroundTruthRecord,
    UiPredictionRecord,
    UiFrameIndexRecord,
    UiEvaluationBundle,
    UiEvaluationConfig,
    UiFailureRecord,
    UiMetrics,
    UiEvaluationResult,
    load_ui_evaluation_bundle,
    evaluate_ui_predictions,
    write_ui_evaluation_result,
)
from bot.perception.ui_inference_runner import (
    load_ui_inference_source,
    load_ui_inference_config,
    run_ui_inference,
    write_ui_inference_result,
    UiInferenceSource,
    UiInferenceConfig,
    UiInferenceResult,
    UiInferenceFrameRecord,
    OcrFieldConfig,
    ButtonTemplateConfig,
)

__all__ = [
    "DEFAULT_AVATAR_LAYOUT",
    "AvatarRoiLayout",
    "ButtonTemplate",
    "FanCardTemplateRecognizer",
    "FanGeometry",
    "CardCountDelta",
    "HighlightDetection",
    "HybridTurnOwnerDetector",
    "HybridTurnOwnerConsensus",
    "NormalizedRect",
    "OcrConfigurationError",
    "OcrText",
    "StateAcceptancePolicy",
    "TableStateAssembler",
    "TableStateConsensus",
    "TableStateConsensusResult",
    "TemplateButtonDetector",
    "TesseractOcr",
    "TurnOwnerDetection",
    "TurnOwnerConsensusResult",
    "YellowHighlightDetector",
    "YoloCardConfigurationError",
    "YoloCardDetector",
    "load_gameplay_button_detector",
    "UiEvaluationStatus",
    "UiButtonState",
    "UiPredictedButtonState",
    "UiOcrField",
    "UiPredictedOcrField",
    "UiGroundTruthRecord",
    "UiPredictionRecord",
    "UiFrameIndexRecord",
    "UiEvaluationBundle",
    "UiEvaluationConfig",
    "UiFailureRecord",
    "UiMetrics",
    "UiEvaluationResult",
    "load_ui_evaluation_bundle",
    "evaluate_ui_predictions",
    "write_ui_evaluation_result",
    "load_ui_inference_source",
    "load_ui_inference_config",
    "run_ui_inference",
    "write_ui_inference_result",
    "UiInferenceSource",
    "UiInferenceConfig",
    "UiInferenceResult",
    "UiInferenceFrameRecord",
    "OcrFieldConfig",
    "ButtonTemplateConfig",
]
